remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme

title: Dan Mazur, PhD
description: Personal website of Dan Mazur, PhD. Dan is a machine learning engineer in Vancouver, BC.

keep_files: [slides/*]
google_analytics: G-TWEE1B2MEN
